"""与 MC1_graph.json 导入 Neo4j 后的约定（scripts/import_data.py 中的关系类型）。"""

# API 请求里可用大写键；值为 Neo4j 中实际 type()（导入脚本为 UPPER_SNAKE_CASE）
DEFAULT_REL_TYPES: dict[str, str] = {
    "PERFORMER_OF": "PERFORMER_OF",
    "IN_STYLE_OF": "IN_STYLE_OF",
    "INTERPOLATES_FROM": "INTERPOLATES_FROM",
    "COMPOSER_OF": "COMPOSER_OF",
    "LYRICIST_OF": "LYRICIST_OF",
    "RECORDED_BY": "RECORDED_BY",
    "DISTRIBUTED_BY": "DISTRIBUTED_BY",
    "COVER_OF": "COVER_OF",
    "LYRICAL_REFERENCE_TO": "LYRICAL_REFERENCE_TO",
    "DIRECTLY_SAMPLES": "DIRECTLY_SAMPLES",
    "MEMBER_OF": "MEMBER_OF",
    "PRODUCER_OF": "PRODUCER_OF",
}

DEFAULT_LABEL_PERSON = "Person"
DEFAULT_LABEL_SONG = "Song"
