"""与 MC1_graph.json 导入 Neo4j 后的约定。"""

DEFAULT_REL_TYPES: dict[str, str] = {
    "PERFORMER_OF": "PERFORMER_OF",
    "IN_STYLE_OF": "IN_STYLE_OF",
    "INTERPOLATES_FROM": "INTERPOLATES_FROM",
    "COMPOSER_OF": "COMPOSER_OF",
    "LYRICIST_OF": "LYRICIST_OF",
    "RECORDED_BY": "RECORDED_BY",
    "DISTRIBUTED_BY": "DISTRIBUTED_BY",
    "COVER_OF": "COVER_OF",
    "LYRICAL_REFERENCE_TO": "LYRICAL_REFERENCE_TO",
    "DIRECTLY_SAMPLES": "DIRECTLY_SAMPLES",
    "MEMBER_OF": "MEMBER_OF",
    "PRODUCER_OF": "PRODUCER_OF",
}
